import { useEffect, useState } from "react";
import Sidebar from "./components/Sidebar.jsx";
import GameCard from "./components/GameCard.jsx";
import Scoreboard from "./components/Scoreboard.jsx";
import WinProbBar from "./components/WinProbBar.jsx";
import ControlPanel from "./components/ControlPanel.jsx";
import { fetchTeams, fetchUpcoming, predictGame } from "./api/client.js";

// Maps a win probability margin to the same confidence tiers the CLI uses.
function confidenceLabel(homeProb) {
  const margin = Math.abs(homeProb - 0.5);
  if (margin >= 0.2) return "Strong favorite";
  if (margin >= 0.1) return "Lean";
  return "Toss-up";
}

// Top-level page: upcoming-games dashboard plus a custom matchup view.
export default function App() {
  const [view, setView] = useState("predictions");
  const [upcoming, setUpcoming] = useState(null);
  const [upcomingError, setUpcomingError] = useState(null);
  const [loadedAt, setLoadedAt] = useState(null);

  const [teams, setTeams] = useState([]);
  const [prediction, setPrediction] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // Load the stored games and their predictions once on mount.
  useEffect(() => {
    fetchUpcoming()
      .then((data) => {
        setUpcoming(data);
        setLoadedAt(new Date());
      })
      .catch((err) => setUpcomingError(err.message));
  }, []);

  // Load the team list once so the custom matchup dropdowns can populate.
  useEffect(() => {
    fetchTeams()
      .then(setTeams)
      .catch(() =>
        setError("Cannot reach the prediction server — is app.py running?")
      );
  }, []);

  // Calls the backend for a one-off prediction and stores the result.
  const handlePredict = async (matchup) => {
    setLoading(true);
    setError(null);
    try {
      setPrediction(await predictGame(matchup));
    } catch (err) {
      setError(err.message);
      setPrediction(null);
    } finally {
      setLoading(false);
    }
  };

  // Clears the current custom prediction and any error state.
  const handleReset = () => {
    setPrediction(null);
    setError(null);
  };

  const winner =
    prediction &&
    (prediction.homeProb >= 0.5 ? prediction.homeTeam : prediction.awayTeam);
  const winnerProb =
    prediction && Math.max(prediction.homeProb, prediction.awayProb);

  return (
    <div className="shell">
      <Sidebar
        view={view}
        onSelectView={setView}
        metrics={upcoming?.metrics}
      />

      <main className="content">
        {view === "predictions" && (
          <>
            <header className="page-head">
              <div>
                <h1 className="page-title">Upcoming Predictions</h1>
                <p className="page-sub">
                  Win probability generated by the model for each matchup
                </p>
              </div>
              {loadedAt && (
                <p className="page-meta">
                  Updated {loadedAt.toLocaleDateString()} ·{" "}
                  {loadedAt.toLocaleTimeString(undefined, {
                    hour: "numeric",
                    minute: "2-digit",
                  })}
                </p>
              )}
            </header>

            {upcomingError && (
              <div className="error-banner card">{upcomingError}</div>
            )}

            {!upcoming && !upcomingError && (
              <p className="empty-note">Loading games…</p>
            )}

            {upcoming?.games?.length === 0 && (
              <p className="empty-note">
                No games stored yet. Run <code>python nba-win-prob/update_odds.py</code>.
              </p>
            )}

            <div className="game-list">
              {upcoming?.games?.map((game) => (
                <GameCard key={game.gameId} game={game} />
              ))}
            </div>
          </>
        )}

        {view === "rankings" && (
          <>
            <header className="page-head">
              <div>
                <h1 className="page-title">Rankings</h1>
                <p className="page-sub">Team power ratings</p>
              </div>
            </header>
            <p className="empty-note">Not built yet.</p>
          </>
        )}

        {view === "custom" && (
          <>
            <header className="page-head">
              <div>
                <h1 className="page-title">Custom Matchup</h1>
                <p className="page-sub">
                  Predict any pairing, with optional injuries
                </p>
              </div>
            </header>

            <ControlPanel
              teams={teams}
              onPredict={handlePredict}
              onReset={handleReset}
              loading={loading}
            />

            {error && <div className="error-banner card">{error}</div>}

            {prediction && (
              <>
                <Scoreboard
                  homeTeam={prediction.homeTeam}
                  awayTeam={prediction.awayTeam}
                  homeScore="—"
                  awayScore="—"
                  period={null}
                  clock="Pre-game"
                />

                <WinProbBar
                  homeTeam={prediction.homeTeam}
                  awayTeam={prediction.awayTeam}
                  homeProb={prediction.homeProb}
                  awayProb={prediction.awayProb}
                />

                <section className="verdict card">
                  <p className="verdict-line">
                    Predicted winner: <strong>{winner}</strong> (
                    {Math.round(winnerProb * 100)}% —{" "}
                    {confidenceLabel(prediction.homeProb)})
                  </p>
                  {prediction.homeMargin != null && (
                    <p className="verdict-line verdict-line--spread">
                      Predicted spread:{" "}
                      <strong>
                        {prediction.homeMargin >= 0
                          ? prediction.homeTeam
                          : prediction.awayTeam}{" "}
                        by {Math.abs(prediction.homeMargin).toFixed(1)}
                      </strong>
                    </p>
                  )}
                  {prediction.adjustments.length > 0 && (
                    <ul className="adjustments">
                      {prediction.adjustments.map((line) => (
                        <li key={line}>{line}</li>
                      ))}
                    </ul>
                  )}
                </section>
              </>
            )}
          </>
        )}
      </main>
    </div>
  );
}
